/**
 * Web Application Firewall (WAF) & Edge Shield Detector (Inspirado no WAFW00F)
 * Inspeciona cabeçalhos, cookies e comportamento de resposta para identificar
 * firewalls de aplicação web e proxies reversos de proteção.
 */

export interface WafSignature {
  id: string;
  name: string;
  vendor: string;
  headerMatches?: Array<{ name: string; valuePattern?: RegExp }>;
  cookieMatches?: RegExp[];
  bodyMatches?: RegExp[];
  statusCodes?: number[];
}

export interface WafDetectionReport {
  targetUrl: string;
  detected: boolean;
  wafName: string;
  vendor: string;
  confidence: "HIGH" | "MEDIUM" | "LOW" | "NONE";
  detectionPhase: "PASSIVE" | "ACTIVE_PROBE" | "NONE";
  indicators: string[];
  recommendation: string;
  durationMs: number;
}

const WAF_SIGNATURES: WafSignature[] = [
  {
    id: "cloudflare",
    name: "Cloudflare Web Application Firewall",
    vendor: "Cloudflare, Inc.",
    headerMatches: [
      { name: "server", valuePattern: /cloudflare/i },
      { name: "cf-ray" },
      { name: "cf-cache-status" },
    ],
    cookieMatches: [/_cfuvid/i, /cf_clearance/i, /__cfduid/i],
    bodyMatches: [/Attention Required! \| Cloudflare/i, /CLOUDFLARE_ERROR_500S_BOX/i, /Cloudflare Ray ID/i],
  },
  {
    id: "aws-waf",
    name: "AWS WAF / Amazon CloudFront Shield",
    vendor: "Amazon Web Services (AWS)",
    headerMatches: [
      { name: "x-amzn-requestid" },
      { name: "x-amz-cf-id" },
      { name: "x-amzn-errortype", valuePattern: /waf/i },
    ],
    cookieMatches: [/aws-waf-token/i, /AWSALB/i, /AWSALBCORS/i],
    bodyMatches: [/Request blocked by AWS WAF/i, /<title>AWS WAF/i, /The request could not be satisfied/i],
  },
  {
    id: "modsecurity",
    name: "ModSecurity (Trustwave / OWASP Core Rule Set)",
    vendor: "OWASP / Trustwave",
    headerMatches: [
      { name: "server", valuePattern: /mod_security|modsecurity/i },
      { name: "x-mod-security" },
    ],
    bodyMatches: [/This error was generated by Mod_Security/i, /OWASP_CRS/i, /blocked by ModSecurity/i],
    statusCodes: [403, 406, 501],
  },
  {
    id: "imperva",
    name: "Imperva Incapsula WAF",
    vendor: "Imperva, Inc.",
    headerMatches: [
      { name: "x-cdn", valuePattern: /incapsula|imperva/i },
      { name: "x-iinfo" },
    ],
    cookieMatches: [/incap_ses_/i, /visid_incap_/i, /nlbi_/i, /___utmvc/i],
    bodyMatches: [/Request unsuccessful\. Incapsula incident ID/i, /_Incapsula_Resource/i],
  },
  {
    id: "akamai",
    name: "Akamai Kona Site Defender / App Protector",
    vendor: "Akamai Technologies",
    headerMatches: [
      { name: "server", valuePattern: /AkamaiGHost|Ghost/i },
      { name: "x-akamai-transformed" },
      { name: "x-akamai-request-id" },
    ],
    cookieMatches: [/ak_bmsc/i, /bm_sz/i, /bm_sv/i],
    bodyMatches: [/Access Denied - Akamai/i, /Reference&#32;&#35;/i, /AkamaiGHost/i],
  },
  {
    id: "azure-waf",
    name: "Microsoft Azure Front Door / Application Gateway WAF",
    vendor: "Microsoft Corporation",
    headerMatches: [
      { name: "x-azure-ref" },
      { name: "x-azure-fdid" },
      { name: "server", valuePattern: /Microsoft-Azure-Application-Gateway/i },
    ],
    cookieMatches: [/ApplicationGatewayAffinity/i],
    bodyMatches: [/Azure Front Door/i, /The request is blocked\. Azure Front Door/i],
  },
  {
    id: "sucuri",
    name: "Sucuri CloudProxy WAF",
    vendor: "Sucuri (GoDaddy)",
    headerMatches: [
      { name: "server", valuePattern: /sucuri/i },
      { name: "x-sucuri-id" },
      { name: "x-sucuri-cache" },
    ],
    cookieMatches: [/sucuri_cloudproxy/i],
    bodyMatches: [/Access Denied - Sucuri Website Firewall/i, /Questions\? cloudproxy@sucuri\.net/i],
  },
  {
    id: "f5-bigip",
    name: "F5 BIG-IP Application Security Manager (ASM)",
    vendor: "F5 Networks",
    headerMatches: [
      { name: "server", valuePattern: /BigIP|BIG-IP/i },
      { name: "x-cnection" },
    ],
    cookieMatches: [/BIGipServer/i, /TS[a-zA-Z0-9]{6,}/i],
    bodyMatches: [/The requested URL was rejected\. Please consult with your administrator/i],
  },
];

export async function detectWaf(targetUrl: string): Promise<WafDetectionReport> {
  const startTime = Date.now();
  let url = targetUrl.trim();
  if (!url.startsWith("http://") && !url.startsWith("https://")) {
    url = `https://${url}`;
  }

  const indicators: string[] = [];
  let detectedWaf: WafSignature | null = null;
  let phase: "PASSIVE" | "ACTIVE_PROBE" | "NONE" = "NONE";
  let confidence: "HIGH" | "MEDIUM" | "LOW" | "NONE" = "NONE";

  // 1. FASE PASSIVA (Baseline Request)
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 4000);

    const baselineRes = await fetch(url, {
      method: "GET",
      signal: controller.signal,
      redirect: "follow",
      headers: {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ObsidianSec/1.2",
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      },
    });

    clearTimeout(timeout);

    const headers = baselineRes.headers;
    const rawSetCookies: string[] = [];
    if (typeof (headers as any).getSetCookie === "function") {
      rawSetCookies.push(...(headers as any).getSetCookie());
    } else {
      const sc = headers.get("set-cookie");
      if (sc) rawSetCookies.push(sc);
    }
    const cookieStr = rawSetCookies.join("; ");

    for (const waf of WAF_SIGNATURES) {
      // Checa headers
      if (waf.headerMatches) {
        for (const hm of waf.headerMatches) {
          const val = headers.get(hm.name);
          if (val !== null) {
            if (!hm.valuePattern || hm.valuePattern.test(val)) {
              indicators.push(`Cabeçalho identificador: '${hm.name}: ${val.slice(0, 50)}'`);
              detectedWaf = waf;
              confidence = "HIGH";
              phase = "PASSIVE";
            }
          }
        }
      }

      // Checa cookies
      if (waf.cookieMatches) {
        for (const cm of waf.cookieMatches) {
          if (cm.test(cookieStr)) {
            indicators.push(`Cookie exclusivo de WAF: padrão '${cm.source}'`);
            detectedWaf = waf;
            confidence = "HIGH";
            phase = "PASSIVE";
          }
        }
      }
    }
  } catch (err: any) {
    indicators.push(`Aviso na inspeção passiva: ${err.message}`);
  }

  // 2. FASE ATIVA BENIGNA (Se não foi conclusivo na fase passiva)
  if (!detectedWaf) {
    try {
      const parsed = new URL(url);
      parsed.searchParams.set("obsidian_waf_probe", "<script>alert('obsidiansec_probe')</script>");

      const probeController = new AbortController();
      const probeTimeout = setTimeout(() => probeController.abort(), 4000);

      const probeRes = await fetch(parsed.toString(), {
        method: "GET",
        signal: probeController.signal,
        headers: {
          "User-Agent": "ObsidianSec-WAF-Probe/1.2 (+https://obsidiansec.dev)",
        },
      });

      clearTimeout(probeTimeout);

      const status = probeRes.status;
      const body = await probeRes.text();
      const headers = probeRes.headers;

      if (status === 403 || status === 406 || status === 429 || status === 501) {
        for (const waf of WAF_SIGNATURES) {
          // Checa assinaturas de corpo HTML de bloqueio
          if (waf.bodyMatches) {
            for (const bm of waf.bodyMatches) {
              if (bm.test(body)) {
                indicators.push(`Padrão de bloqueio de WAF detectado no corpo da resposta: '${bm.source}'`);
                detectedWaf = waf;
                confidence = "HIGH";
                phase = "ACTIVE_PROBE";
                break;
              }
            }
          }
        }

        if (!detectedWaf) {
          detectedWaf = {
            id: "generic-waf",
            name: "Firewall / WAF Genérico (Bloqueio Detectado)",
            vendor: "Desconhecido / Provedor Customizado",
          };
          indicators.push(`A requisição de teste retornou HTTP ${status} (Bloqueio de ataque sintético).`);
          confidence = "MEDIUM";
          phase = "ACTIVE_PROBE";
        }
      }
    } catch {
      // Ignora falha na fase ativa
    }
  }

  const isDetected = detectedWaf !== null;
  const wafName = isDetected ? detectedWaf.name : "Nenhum WAF Detectado (Exposição Direta ao Servidor)";
  const vendor = isDetected ? detectedWaf.vendor : "Servidor Web Convencional";

  let recommendation = "WAF ativo e monitorando requisições de borda.";
  if (!isDetected) {
    recommendation = "Recomendado colocar a aplicação atrás de um WAF (ex: Cloudflare WAF, AWS WAF ou ModSecurity) para mitigar ataques automatizados de injeção SQL, XSS e botnets.";
  }

  return {
    targetUrl: url,
    detected: isDetected,
    wafName,
    vendor,
    confidence,
    detectionPhase: phase,
    indicators,
    recommendation,
    durationMs: Date.now() - startTime,
  };
}